global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['34.134.254.172:9090']  ##update your local IP/localhost

  - job_name: 'node'
    static_configs:
      - targets: ['34.134.254.172:9100']  ##update your local IP/localhost

    #remote_write:
    #  - url: '<Your Prometheus remote_write endpoint>'
     #   basic_auth:
       #   username: '<Your Grafana Username>'
      #    password: '<Your Grafana API key>'

#sudo docker inspect --format '{{ .State.Pid }}' container_name
#sudo kill -9 <pid>
